# Use the official Node.js 23-alpine image as the base image
FROM node:24-alpine

# Install necessary packages: pnpm, screen, and vim
RUN apk add --no-cache \
  bash \
  zip \
  tmux \
  vim \
  && npm install -g pnpm

# Set the working directory
WORKDIR /app

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the application
CMD ["tail", "-f", "/dev/null"]